# Generated by Django 3.2.5 on 2021-07-16 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0004_auto_20210716_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('qty', models.IntegerField(default=0)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=100, null=True)),
                ('received_from', models.CharField(blank=True, max_length=100, null=True)),
                ('received_comment', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivegood_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_goods', to='stores.product')),
                ('updated_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivegood_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
