# Generated by Django 3.2.5 on 2021-07-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20210716_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
