# Generated by Django 3.2.5 on 2021-07-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_rename_city_supplier_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivegood',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
