# Generated by Django 3.2.5 on 2021-07-18 11:30

from django.db import migrations, models
import stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_auto_20210718_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivegood',
            name='purchase_order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receivegood',
            name='purchase_order',
            field=models.FileField(blank=True, null=True, upload_to=stores.models.purchase_order_path),
        ),
    ]
